### ISSUE TITLE
Including abundances in kernel estimation?

### ISSUE THREAD

**Issue by maxfarrell** [mikemeredith/overlap#3]
I am wondering if it is possible to include abundances in the estimation of densities?

I have a system in which multiple animals are present in a single photograph, and would like to use this information when calculating the activity patterns, rather than implicitly treating activitiy as a binary (present in a photo or not). 

I can't find any mention of this in the documentation. Is this possible with the package? I was thinking a hack would be to extend the data frame so that there is a new line for every individual per photo, but this would dramatically increase the size of the dataframe, and it seems like there should be an easy way to incorporate this into the density estimation.

Thank you for your time

**Comment by mikemeredith** [comment]
That's not a good idea. There is an underlying assumption that observations are independent, and treating multiple animals in the same photo as multiple observations violates that.

A photo of species X taken at 04:36 tells you that the species is active at 04:36, no matter how many individuals are in the photo. If you had lots of independent photos with times between 04:00 and 05:00 you could infer that lots of activity was taking place in that period.

If you want to do it anyway, no need to modify the data frame. If `t` is the vector of times and `n` is a matching vector of number of individuals, just do `t1 <- rep(t, n)`.
