### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by Eleonore33** [mikemeredith/overlap#4]
Hello,
I am new to R so sorry if this is a trivial question.
I have been working through the overlap package, and did a first try with the kerinci data base. However, the bootstrap part displays an error: 
"Error in matrix(sample(x, size = n * nboot, replace = TRUE), nrow = nboot) : 
  data is too long" 

I have tried with my own data set which is in the same format as the kerinci one and I also had an error as such: 
"Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'theta' of mode 'function' was not found"

I can't find any one who had the same issue so I figured out I would post here.

Thanks,

**Comment by mikemeredith** [comment]
Hi Eleonore,

Sorry you had a problem with `overlap` and especially that you got unhelpful error messages. To be able to help I need to reproduce the error. You don't even say what function gave the error! Can you give me code for a minimum reproducible example? You could start with the Example code on the `?kerinci` help page (which doesn't produce the error) and modify it to give the error. I'd also need to know the versions of R and packages, so run `sessionInfo()` and copy the output into your reply.

Thanks, Mike
