### ISSUE TITLE
Bootstrap Est and CI

### ISSUE THREAD

**Issue by Emma278** [mikemeredith/overlap#5]
Hi!

First of all, thank you for creating such a great and easy program for estimating overlap.

I am very new to R and coding in general, so apologies for the very simple question, I hope you don't mind I post it on here.

When reporting estimates of overlap and CI do I use the final BootEst value or the OverlapEst value, with the BootCI intervals?

Thank you so much for your help!

**Comment by mikemeredith** [comment]
This is not a software issue and should not be posted here. You can email the maintainer at the contact in the package DESCRIPTION file.

Please check the package vignette, `vignette("overlap", package="overlap")` section 4.1 - we recommend adjusting the output from `overlapEst` without adjustment.
