### ISSUE TITLE
bootstrap function error

### ISSUE THREAD

**Issue by Pronghorn1** [mikemeredith/overlap#6]
Hi Mike,

Thanks for creating a wonderful package to fit kernel density functions to data on temporal activity patterns of animals.  I have been learning the overlap package by using the example data and code,, as well as playing with some of my own camera trap data.

Whether using the sample data or my own I am getting the following error message related to the bootstrap function:

Error in bootstrap(spsA, spsB, 999, type = "Dhat1") : 
  could not find function "bootstrap" 

Do you know why I am getting this error message?  I am using version 0.3.2 of the overlay package.  Code I used is as follows:

> data(kerinci)
> str(kerinci)
> range(kerinci$Time)
> timeRad <- kerinci$Time * 2*pi
> spsA <- timeRad[kerinci$Zone == 3 & kerinci$Sps == 'tiger']
> spsB <- timeRad[kerinci$Zone == 3 & kerinci$Sps == 'tapir']
> overlapPlot(spsA, spsB) # Tapir are mainly nocturnal
> overlapPlot(spsA, spsB, xcenter="midnight")
> legend('topleft', c("Tiger", "Tapir"), lty=c(1, 2), col=c("black", "blue"), bty='n')
> length(spsA)
> length(spsB)
> ( Dhat1 <- overlapEst(spsA, spsB, type="Dhat1") )
> bs <- bootstrap(spsA, spsB, 999, type="Dhat1")
Error in bootstrap(spsA, spsB, 999, type = "Dhat1") : 
  could not find function "bootstrap"

Thanks,

Paul

**Comment by mikemeredith** [comment]
Hi Paul,

Pleased to know that you find the package useful.

The `overlap::bootstrap` function is new in version 0.3.3 and you have the old version. You need to update you packages.

Always a good idea to update packages before posting an issue!
